name: scrizer
description: "A lightweight and scalable UI toolkit for Flutter that provides responsive typography, spacing, and layout utilities based on screen size and orientation."
version: 1.3.0 

# Author and metadata
homepage: https://github.com/Mbouziani/Scrizer
repository: https://github.com/Mbouziani/Scrizer

# SDK compatibility
environment:
  sdk: ^3.7.2
  flutter: '>=3.3.0'


# Dependencies
dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

# Dev dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# Flutter plugin configuration
flutter:
  plugin:
    platforms:
      android:
        package: com.example.scrizer
        pluginClass: ScrizerPlugin
      ios:
        pluginClass: ScrizerPlugin
      web:
        pluginClass: ScrizerPlugin
      macos:
        pluginClass: ScrizerPlugin
      windows:
        pluginClass: ScrizerPlugin
      linux:
        pluginClass: ScrizerPlugin

# Additional configurations (if applicable)
documentation: https://github.com/Mbouziani/Scrizer/blob/main/README.md