name: scrizer
description: "A lightweight and scalable UI toolkit for Flutter that provides responsive typography, spacing, and layout utilities based on screen size and orientation."
version: 1.3.4

# Author and metadata
homepage: https://github.com/Mbouziani/Scrizer
repository: https://github.com/Mbouziani/Scrizer

# SDK compatibility
environment:
  sdk: ^3.7.2
  flutter: '>=3.3.0'


# Dependencies
dependencies:
  dartz: ^0.10.1
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

# Dev dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# Flutter plugin configuration
# ✅ Move plugin here
plugin:
  platforms:
    android:
      package: com.example.scrizer
      pluginClass: ScrizerPlugin
      fileName: scrizer.dart
    ios:
      pluginClass: ScrizerPlugin
      fileName: scrizer.dart
    web:
      pluginClass: ScrizerPlugin
      fileName: scrizer.dart
    macos:
      pluginClass: ScrizerPlugin
      fileName: scrizer.dart
    windows:
      pluginClass: ScrizerPlugin
      fileName: scrizer.dart
    linux:
      pluginClass: ScrizerPlugin
      fileName: scrizer.dart

flutter:
  uses-material-design: true

# Additional configurations (if applicable)
documentation: https://github.com/Mbouziani/Scrizer/blob/main/README.md